### PR TITLE
Shorten Windows installation command.

### PR DESCRIPTION
**Pull request by YouJiacheng**
#19

### CODE REVIEW

**Comment by pavelzw** [comment]
I don't really have strong opinions but I've also seen `iwr -useb` in some other places instead of `irm`. ChatGPT says that `irm` is typically used when dealing with APIs that return structured data like XML or JSON. Maybe `Invoke-WebRequest` makes more sense here since this is only a plain file?

**Comment by YouJiacheng** [comment]
I saw Powershell itself use irm
https://github.com/PowerShell/PowerShell/blob/504b6e0e6be5498421ccf01b1ae087f2cde7bcca/tools/install-powershell.ps1#L25

**Review by pavelzw — APPROVED** [review]
It might make sense to write some CI tests at some point as we do for `install.sh`

**Comment by pavelzw** [comment]
@AntoinePrv

**Comment by AntoinePrv** [comment]
I don't have much knowledge about anything Windows :/

**Comment by jjerphan** [comment]
Well spotted, but unfortunately, but I do not think we need to address this cosmetic changes unless strictly required.

**Pull request closed without merging**
